Multilinguall_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bodyapp/', include("bodyapp.urls"))
]

bodyapp/urls.py
from django.urls import path

from . import views


app_name = "bodyapp"
urlpatterns = [
    path("", views.signin, name="index"),
    path("home", views.home, name="home"),
    path("home/head", views.head, name="head"),
    path("home/manbody", views.manbody, name="manbody")
]

bodyapp/models.py
from django.db import models

# Create your models here.

class UserReg(models.Model):
    username = models.CharField(max_length=100)
    usermail = models.EmailField(max_length=300)


    def __str__(self):
        return f"{self.id}: {self.username} and {self.usermail}"

bodyapp/views.py
from email import message
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from . models import UserReg

# Create your views here.

def home(request):
    return render(request, "bodyapp/index.html")


def head(request):
    return render(request, "bodyapp/head.html")


def manbody(request):
    return render(request, "bodyapp/manbody.html")

def signin(request):

    if request.method == "POST":
        username = request.POST["name"]
        usermail = request.POST["email"]
        details = UserReg(username = username, usermail = usermail)
        if username !="" and usermail !="":
            check_existing = UserReg.objects.filter(username=username) and UserReg.objects.filter(usermail=usermail).exists()
            if check_existing:
                message1 = "user already exists"
                return render(request, "bodyapp/signup.html", {
                    "message1": message1
                })
                return HttpResponseRedirect(reverse("bodyapp:index"))
            else:    
                details.save()
                return HttpResponseRedirect(reverse("bodyapp:home"))
            
            
            
        else:
            message ="Please enter valid input"
            return render(request, "bodyapp/signup.html", {
                "message": message
            })
    return render(request, "bodyapp/signup.html")

bodyapp/templates/bodyapp/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MultiLingual Body Parts</title>

    <!-- FONT STYLES -->
    <link rel="stylesheet" href="{% static 'stylesheets/fonts.css' %}">
    <!-- ICON STYLES -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

    <!-- default external stylesheet-->
    <link rel="stylesheet" href="{% static 'stylesheets/style.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheets/lightslider.css' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/lightslider.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>


</head>
<body>

    <section>
        <div class="container">
            <!-- SLIDER  -->
            <ul id="autoWidth" class="cs-hidden">
                <!-- ITEM 1 -->
                <li class="item-a">
                <a href="{% url 'bodyapp:manbody' %}"><div class="box">
                            <p class="home-text">MAN</p>
                            <img src="{% static 'images/man-slider.png' %}"  alt="Man image" class="model">
                    </div>
                </a>
                </li>

                <li class="item-b">
                    <a href="{% url 'bodyapp:head' %}">
                        <div class="box">
                            <p class="home-text">HEAD</p>
                            <img src="{% static 'images/head-slider.png' %}" alt="Man image" class="model" id="head-slider">
                        </div>
                    </a>
                </li>
            </ul>
            
        </div>
    </section>
    
</body>
</html> 

bodyapp/templates/bodyapp/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>sign in</title>
        <link rel="stylesheet" href="{% static 'stylesheets/signin.css' %}">
    </head>
    <body>
        <section>
            <div class="form-container">
                <h1>Login Form</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="control">
                        <label for="name">Name</label>
                        <input type="text" name="name" id="name">
                    </div>
                    <div class="control">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email">
                    </div>
                    <span><input type="checkbox"> Remenber me</span>
                    <div class="control">
                        <input type="submit" value="Login">
                        {% if message1 %}
                        <p class="messa"> {{ message1 }}.
                            signed up before ?
                            <br>
                            <a href="{% url 'bodyapp:home' %}">Go to homepage</a>
                        </p>
                        {% endif %}
                        {% if message %}
                        <p class="messa"> {{ message }} </p>
                        {% endif %}
                    </div>
                </form>
            </div>
        </section>
    </body>
</html>